language: java
jdk: openjdk8
install:
  - skip
matrix:
  include:
    - name: Maven
      script:
        - mvn test -B -Dgpg.skip=true
    - name: Gradle
      script:
        - git config --list
        - cat -e mvn.bat
        - cat -e make_bundle.cmd
        - cat -e scripts/javacc.bat
        - ./gradlew --no-daemon build javadoc
